version: '3'
services:
  db:
    container_name: pokedex_db
    image: library/mariadb:10.6.4
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: app_data
      MYSQL_USER: app_user
      MYSQL_PASSWORD: devsecret
      MYSQL_ROOT_PASSWORD: devroot